In [1]:
import numpy as np

In [2]:
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [3]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [4]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [5]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [6]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [7]:
numero_random = np.random.randint(
    11 # [0, 11[
)
numero_random

4

In [8]:
numero_random_negativo = np.random.randint(
    -9,  # [-9, 2[
    2
)
numero_random_negativo

-4

In [9]:
arreglo_random = np.random.randint(
    10,
    20,
    8
)
arreglo_random

array([15, 13, 18, 14, 12, 17, 19, 11])

In [10]:
np.random.rand(9) # 9 Elementos
np.random.rand(3,2) # 6 Elementos (3 x 2 dimensiones)

array([[0.36460113, 0.97051171],
       [0.09087671, 0.95949333],
       [0.70009041, 0.50919959]])

In [11]:
np.average(arreglo_random)

14.875

In [12]:
np.mean(arreglo_random)

14.875

In [13]:
np.median(arreglo_random)

14.5

In [14]:
np.std(arreglo_random)

2.7128168017763383

In [15]:
np.var(arreglo_random)

7.359375

In [16]:
arreglo_random.mean()

14.875