In [2]:
# 1) Examen
import numpy as np

In [4]:
## 2) Crear un vector de ceros de tamaño 10
vector_ceros=np.zeros(10)
print(vector_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
vector_ceros=np.zeros(10)
vector_ceros[4]=1
print(vector_ceros)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.
print("\nvector en orden\n")
vector_A=tuple(range(1,51))
print(vector_A)
vector_B=vector_A[::-1]
print("\nvector invertido\n")
print(vector_B)
#print(vector_B)


vector en orden

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50)

vector invertido

(50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1)


In [42]:
## 5) Crear una matriz de 3 x 3 con valores del cero al 8
matriz_A = np.arange(9).reshape(3,3)
print(matriz_A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
## 6) Encontrar los indices que no sean cero en un arreglo

arreglo = [1,2,0,0,4,0]

arreglo_sin_ceros=np.nonzero(arreglo)
print("Los indices de los valores diferentes a cero son:")
print(arreglo_sin_ceros)


Los indices de los valores diferentes a cero son:


(array([0, 1, 4], dtype=int64),)

In [33]:
## 7) Crear una matriz de identidad 3 x 3 
m_identidad=np.identity(3)
print(m_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
## 8) Crear una matriz 3 x 3 x 3 con valores randomicos

matriz_B=np.random.random((3, 3, 3))
matriz_B

array([[[0.80172541, 0.32706044, 0.69738963],
        [0.61315902, 0.58740159, 0.55959355],
        [0.34559546, 0.13703703, 0.08900997]],

       [[0.19500138, 0.56877432, 0.46130136],
        [0.99016559, 0.50627706, 0.18349795],
        [0.55620589, 0.6963645 , 0.22838096]],

       [[0.41353821, 0.420797  , 0.88110715],
        [0.50919389, 0.9424855 , 0.74843035],
        [0.08237915, 0.81845317, 0.59241832]]])

In [49]:
## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor
matriz_B=np.random.random((10, 10,))
print(matriz_B)
print("///////////////////////////////////////////////")
menor=np.amin(matriz_B)
print(f'El elemento menor es:{menor}')
print("///////////////////////////////////////////////")
mayor=np.amax(matriz_B)
print(f'El elemento mayor es:{mayor}')


[[0.19562091 0.36424009 0.64317628 0.03915107 0.24786163 0.21335905
  0.53302627 0.95534042 0.80842732 0.59611446]
 [0.07199508 0.74918207 0.10857133 0.61833041 0.54257816 0.95888115
  0.20002603 0.63920086 0.9318296  0.03531099]
 [0.92849229 0.29553379 0.07594475 0.7222992  0.50413441 0.78925437
  0.6318271  0.8662526  0.04678749 0.29550939]
 [0.27568112 0.66436514 0.67094502 0.2814561  0.19971561 0.29824642
  0.54755618 0.04570774 0.46450455 0.18620216]
 [0.03233436 0.56990052 0.05847391 0.88701735 0.79095885 0.07345966
  0.91995595 0.70485148 0.80260372 0.60022734]
 [0.69500019 0.85519932 0.25552013 0.80710372 0.99328681 0.89545173
  0.55621706 0.01299266 0.19412819 0.76016822]
 [0.71726916 0.33597748 0.2381744  0.09326771 0.75379137 0.14568882
  0.1205844  0.26251008 0.76943283 0.03581624]
 [0.55622471 0.54894766 0.77873167 0.99725863 0.67248613 0.32673671
  0.10067305 0.13530346 0.42160538 0.03057725]
 [0.50395995 0.08958843 0.88600147 0.39673286 0.87691333 0.40382728
  0.42990116

In [57]:
## 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)
from scipy import misc
from scipy import ndimage

imagen_A = misc.face()
colores_rgb=np.unique(imagen_A.reshape(-1,imagen_A.shape[2]),axis=0)
print(colores_rgb)

[[  0   0   5]
 [  0   0   7]
 [  0   0   9]
 ...
 [255 248 255]
 [255 249 255]
 [255 252 255]]


In [65]:
## 11) ¿Como crear una serie de una lista, diccionario o arreglo?
#python
import pandas as pd
import numpy as np

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

serieLista_A = pd.Series(mylist)

serieDic = pd.Series(mydict)

serieArreglo = pd.Series(myarr)

print(serieLista)
print("////////////////////////////////////abs////////")
print(serieDic)
print("////////////////////////////////////////////")
print(serieArreglo)



0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
////////////////////////////////////abs////////
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64
////////////////////////////////////////////
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32


In [75]:
## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?


mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice

#d = {'col1': ser}
#df = pd.DataFrame(data=d)
#df

#d = {'col1': mylist}
#df = pd.DataFrame(data=d)
#df

#d = {'col1': myarr}
#df = pd.DataFrame(data=d)
#df

d = {'col1': mydict}
df = pd.DataFrame(data=d)
df

col1
a     0
b     1
c     2
d     4
e     3
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25

In [73]:

## 13) ¿Como combinar varias series para hacer un DataFrame?

import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

d1 = {'col1': ser1, 'col2': ser2}
df1 = pd.DataFrame(data=d)
df1


col1 col2
a     0    a
b     1    b
c     2    c
e     3    e
d     4    d
f     5    f
g     6    g
h     7    h
i     8    i
j     9    j
k    10    k
l    11    l
m    12    m
n    13    n
o    14    o
p    15    p
q    16    q
r    17    r
s    18    s
t    19    t
u    20    u
v    21    v
w    22    w
x    23    x
y    24    y
z    25    z

In [79]:
## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
resp = ser1.isin(ser2)
for i in range(len(resp)):
  resp[i] = not resp[i]

ser1[resp]

SyntaxError: unexpected EOF while parsing (<ipython-input-79-b9933c0acfd2>, line 9)

In [76]:

## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

a_no_en_b = ser1[~ser1.isin(ser2)]
b_no_en_a = ser2[~ser2.isin(ser1)]
no_comunes_a_b = np.append(a_no_en_b, b_no_en_a)
print(f'Los items que no son comunes en A y B son: {no_comunes_a_b} ')

Los items que no son comunes en A y B son: [1 2 3 6 7 8] 


In [ ]:
## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?

```python
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
```

In [ ]:
## 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

```python
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
```

In [ ]:
## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?


```python
ser = pd.Series(np.random.randint(1, 10, 35))
shape(7,5)
```

In [ ]:
## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?


```python
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
```

In [ ]:
## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?


```python
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
```



In [51]:
## 21)¿Obtener la media de una serie agrupada por otra serie?

`groupby` tambien esta disponible en series.


```python
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64

```

SyntaxError: invalid syntax (<ipython-input-51-7118a4661e4a>, line 3)

In [ ]:
## 22)¿Como importar solo columnas especificas de un archivo csv?

https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv.




